# [
# arn:aws:iam::695834901730:role/gha-test-branch_default
# arn:aws:iam::695834901730:role/gha-test-branch_wildcard
# arn:aws:iam::695834901730:role/gha-test-org_repo
# arn:aws:iam::695834901730:role/gha-test-org_wildcard
# arn:aws:iam::695834901730:role/gha-test-pull_request
# arn:aws:iam::695834901730:role/gha-test-tag
# ]
name: branch-default.yml
on:
  pull_request:
  push:
permissions:
  id-token: write
jobs:
  credentials:
    runs-on: ubuntu-latest
    environment: not-production
    steps:
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::695834901730:role/gha-test-branch_default
          aws-region: us-west-2
      - name: Read S3 bucket
        run: |
          aws s3api get-object --bucket ryanwholey-test-terraform-state --key object foo | cat
