name: Format Terraform Cloud Variables
on:
  workflow_call:
    inputs:
      terraform_version:
        required: true
        type: string
        description: Terraform version
      apply:
        required: true
        type: boolean
        description: Whether to apply the Terraform workspace plan
    secrets:
      terraform_token:
        required: true
        description: A Terraform Cloud token
    outputs:
      variables:
        description: The formatted variables as a JSON list
        value: ${{ jobs.format-variables.outputs.variables }}
jobs:
  format-variables:
    runs-on: ubuntu-latest
    outputs:
      variables: ${{ steps.provider.outputs.output }}
    steps:
      - name: Fetch Workspace Variables
        uses: ryanwholey/terraform-cloud-remote-state-action@main
        id: provider
        with:
          workspace: terraform-credential-provider
          organization: ryanwholey
          address: https://app.terraform.io
          token: ${{ secrets.terraform_token }}
          target: variables
      - uses: TakeScoop/terraform-cloud-workspace-action@v2
        name: Manage Terraform Workspaces
        id: terraform
        with:
          variables: |-
            ${{ steps.provider.outputs.output }}
          terraform_version: ${{ inputs.terraform_version }}
          terraform_token: "${{ secrets.terraform_token }}"
          terraform_organization: ryanwholey
          terraform_host: app.terraform.io
          apply: ${{ inputs.apply }}
          vcs_type: github
          global_remote_state: true
          tags: |-
            - add-provider-config
