name: Send request

on:
  push:
  pull_request:

jobs:
  get_remote_state:
    runs-on: ubuntu-latest
    name: Test fetch remote state
    steps:
      - name: Write manager backend
        id: manager-backend
        run: |-
          file="${{github.workspace}}/manager.tfbackend"
          tee "$file" << EOF
            workspaces { name = "terraform-workspace-manager" }
            hostname     = "app.terraform.io"
            organization = "ryanwholey"
          EOF
          echo "::set-output name=file::$file"
      - name: Get remote state
        uses: dflook/terraform-remote-state@v1
        id: manager
        env:
          TERRAFORM_CLOUD_TOKENS: app.terraform.io=${{ secrets.TF_TOKEN }}
        with:
          backend_type: remote
          backend_config: ${{ steps.manager-backend.outputs.file }}
      - run: echo ${{ steps.manager.outputs.storage_bucket }}
