name: Send request

on:
  push:
  pull_request:

jobs:
  get_remote_state:
    runs-on: ubuntu-latest
    name: Check terraform file are formatted correctly
    steps:
      - name: Write backend config file
        uses: DamianReeves/write-file-action@master
        with:
          path: ${{github.workspace}}/terraform-backend-config.hcl.json
          contents: |
            {
              "workspaces": [
                {
                  "name": "terraform-workspace-manager"
                }
              ],
              "hostname": "app.terraform.io",
              "organization": "ryanwholey"
            }
          write-mode: overwrite
      - name: Get remote state
        uses: dflook/terraform-remote-state@v1
        id: remote-state
        env:
          TERRAFORM_CLOUD_TOKENS: app.terraform.io=${{ secrets.TF_TOKEN }}
        with:
          backend_type: remote
          workspace: default
          backend_config: ${{github.workspace}}/terraform-backend-config.hcl.json
