name: Terraform Cloud Workspace
on:
  pull_request:
    paths:
      - .github/workflows/terraform-workspace.yml
  push:
    branches:
      - main
    paths:
      - .github/workflows/terraform-workspace.yml
  workflow_dispatch:
    inputs:
      apply:
        description: Whether to apply changes to the Terraform workspace. If false, the workflow will print any planned changes but will not apply them.
        required: true
        default: 'false'
permissions:
  checks: write
jobs:
  workspace:
    uses: ryanwholey/terraform-credential-provider/.github/workflows/consumer-workspace.yml@main
    with:
      terraform_version: '1.1.3'
      apply: ${{ github.event.inputs.apply == 'true' || github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
      add_organization_variables: true
      tags: '["tag"]'
    secrets:
      variables: |- 
        [{
          "category": "env",
          "key": "foo",
          "value": "${{ secrets.FOO }}",
          "sensitive": false,
          "description": "just your friendly neighborhood foo"
        }]
      terraform_token: ${{ secrets.TF_TOKEN }}