name: Terraform Cloud Workspace
on:
  pull_request:
    paths:
      - .github/workflows/terraform-workspace.yml
  push:
    branches:
      - master
    paths:
      - .github/workflows/terraform-workspace.yml
  workflow_dispatch:
    inputs:
      apply:
        description: Whether to apply changes to the Terraform workspace. If false, the workflow will print any planned changes but will not apply them.
        required: true
        default: 'false'
permissions:
  checks: write
jobs:
  workspace:
    runs-on: ubuntu-latest
    steps:
      - uses: ryanwholey/terraform-cloud-remote-state-action@main
        with:
          workspace: terraform-workspace-manager
          organization: ryanwholey
          address: https://app.terraform.io
          token: ${{ secrets.TF_TOKEN }}
