name: Terraform Cloud Workspace
on:
  pull_request:
    paths:
      - .github/workflows/terraform-workspace.yml
  push:
    branches:
      - main
    paths:
      - .github/workflows/terraform-workspace.yml
  workflow_dispatch:
    inputs:
      apply:
        description: Whether to apply changes to the Terraform workspace. If false, the workflow will print any planned changes but will not apply them.
        required: true
        default: 'false'
permissions:
  # checks: write
  id-token: write
jobs:
  credentials:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::695834901730:role/test-terraform-state
          aws-region: us-west-2
      - name: Read S3 bucket
        run: |
          aws s3api get-object --bucket ryanwholey-test-terraform-state --key object foo | cat
    # workspace:
  #   uses: ryanwholey/terraform-credential-provider/.github/workflows/consumer-workspace.yml@main
  #   with:
  #     terraform_version: '1.1.3'
  #     apply: ${{ github.event.inputs.apply == 'true' || github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
  #     add_organization_variables: true
  #     tags: '["tag"]'
  #   secrets:
  #     variables: |- 
  #       [{
  #         "category": "env",
  #         "key": "foo",
  #         "value": "${{ secrets.FOO }}",
  #         "sensitive": false,
  #         "description": "just your friendly neighborhood foo"
  #       }]
  #     terraform_token: ${{ secrets.TF_TOKEN }}


      