name: Terraform Cloud Workspace
on:
  pull_request:
    paths:
      - .github/workflows/terraform-workspace.yml
  push:
    branches:
      - master
    paths:
      - .github/workflows/terraform-workspace.yml
  workflow_dispatch:
    inputs:
      apply:
        description: Whether to apply changes to the Terraform workspace. If false, the workflow will print any planned changes but will not apply them.
        required: true
        default: 'false'
permissions:
  checks: write
jobs:
  workspace:
    runs-on: ubuntu-latest
    steps:
      - id: workpsace-outputs
        uses: dflook/terraform-remote-state@v1
        env:
          TERRAFORM_CLOUD_TOKENS: |
            app.terraform.io=${{ secrets.TF_TOKEN }}
        with: 
          backend_type: remote
          workspace: terraform-workspace-manager
          backend_config: |
            organization=ryanwholey
            hostname=app.terraform.io
            name=terraform-workspace-manager
