name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.inputs.tags }}
      # - name: Setup Go
      #   uses: actions/setup-go@v2
      #   with:
      #     go-version: 1.17
      # - name: Release
      #   env:
      #     GOPROXY: proxy.golang.org
      #   run: go list -m github.com/ryanwholey/go-pihole@v0.0.3
 