name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Check output
        run: |
          echo ${{ steps.vars.outputs.tag }}
      # - name: Setup Go
      #   uses: actions/setup-go@v2
      #   with:
      #     go-version: 1.17
      # - name: Release
      #   env:
      #     GOPROXY: proxy.golang.org
      #   run: go list -m github.com/ryanwholey/go-pihole@v0.0.3
 