name: Test github-script Action
on:
  pull_request:
    paths:
      - .github/workflows/test-merge-json-array.yml
  push:
    branches:
      - main
    paths:
      - .github/workflows/test-merge-json-array.yml
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - id: simulate-fetch
        run: echo '::set-output name=fetched::["foo", "bar"]'
      - id: simulate-input
        run: |-
          str=["baz","woz"]
          echo "::add-mask::$str"
          echo "::set-output name=input::$str"
      - uses: actions/github-script@v5
        id: result
        with:
          script: |-
            const first = "${{ steps.simulate-input.outputs.input }}[0]"
            console.log(first)
            
            // const first = ${{ steps.simulate-input.outputs.input }}[0]

            // if (${{ steps.simulate-input.outputs.input }}[0] === '*') {
            //   console.log('masked in template')
            // } else {
            //   console.log('no')
            // }

            return []
      - run: echo ${{ steps.result.outputs.result }}
