name: Terraform Cloud Workspace
on:
  pull_request:
  push:
  workflow_dispatch:
jobs:
  test-mask:
    runs-on: ubuntu-latest
    steps:
      - id: secret
        run: |
          echo "::add-mask::$SECRET"
          echo "::set-output name=number::$SECRET"
        env:
          SECRET: |-
            {
              "foo": "bar",
              "baz": "woz"
            }
      - run: |
          echo "the secret number is ${{ steps.secret.outputs.number }}"
